name: Overall CI/CD for the repository

on:
  push:
    paths:
    - 'version.txt'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Update README.md
      run: |
        VERSION=$(cat version.txt)
        sed -i "s/{{CURRENT_VERSION}}/$VERSION/g" README.md
        # Displaying the content of README.md for verification
        cat README.md

    - name: Commit and push if it changed
      run: |
        git diff
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git commit -am "Update README with new version" || exit 0
        git push https://${{secrets.UPDATE_README_SECRET}}@github.com/rich-dobbs-13440/chromatofore-octoprint-plugin.git
